<a href="https://colab.research.google.com/github/erick1439/CAP4630-Wocjan/blob/master/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**The method below takes a list of numpy arrays and multiples them. If any pair of matrices are not compatible on the list, then the method will return 'None' after printing a messge showing the two arrays, with uncompatible dimensions, that are causing the problem.**

## Two matrices can be multiplied only when their inner dimensions are the same. The dimension of the result will be the outer dimesions of the two multiplied matrices.

Valid Multiplication:

$$\begin{bmatrix}
    a  &  b      \\
    c  &  d
\end{bmatrix}
\times
\begin{bmatrix}
    e  &  f  &  g      \\
    h  &  i  &  j
\end{bmatrix}
=
\begin{bmatrix}
    (a \times e) + (b \times h)  &  (a \times f) + (b \times i)  &  (a \times g) + (b \times j)      \\
    (c \times e) + (d \times h)  &  (c \times f) + (d \times i)  &  (c \times g) + (d \times j)      \\
\end{bmatrix}$$


Invalid Multiplication:

$$\begin{bmatrix}
    a  &  b      \\
    c  &  d
\end{bmatrix}
\times
\begin{bmatrix}
    e  &  f  &  g  \\
    h  &  i  &  j  \\
    k  &  l  &  m
\end{bmatrix}$$



In [0]:
import numpy as np

def multiply_matrices(numpy_Arrays):

  # Bases cases two check if the array is empty or only has one matrix.
  if len(numpy_Arrays) == 0:
    print("The array is empty.")
    return None
  
  if len(numpy_Arrays) == 1:
    return array[0]

  # Creating an identity matrix with the inner dimension of the first numpy 
  # array to store all the matrix computations.
  result = np.identity(numpy_Arrays[0].shape[0], int)
  
  i = 0;

  # Loop that will go through the list multipling all the matrices and throw an 
  # exception if they do not have
  # the proper dimensions.
  try:
    while (i < len(numpy_Arrays)):

      # Conditional that changes the default shape from (R,) to (R,1). 
      # (R represents integer > 0)
      if numpy_Arrays[i].shape == (numpy_Arrays[i].shape[0],):
        numpy_Arrays[i] = numpy_Arrays[i].reshape(numpy_Arrays[i].shape[0], 1)

      result = result.dot((numpy_Arrays[i]))
      i += 1

  except:
    print("the folloing arrays are not compatible:", end="\n\n")
    print(numpy_Arrays[i-1], end="\n\n")
    print(numpy_Arrays[i], end="\n\n")
    return None

  else: 
    return result

# **The following blocks contain different custom test cases that show the output of the "multiply_matrices" method.**

###**Note**: Run the cellBlock with the method before the blocks with the test cases.

In [3]:
# Test case 1: Multiplication of three 3X3 matrices

a = np.array([(1,2,3),(4,5,6),(7,8,9)])
b = np.array([(1,2,3),(4,5,6),(7,7,9)])
c = np.array([(1,2,3),(4,5,6),(7,8,9)])
array = [a,b,c]

print(multiply_matrices(array))


[[ 456  561  666]
 [1038 1275 1512]
 [1620 1989 2358]]


In [0]:
# Test case 2: Multiplication of a 3X2, 2X4, and 4X3

a = np.array([(1,2),(4,5),(7,5)])
b = np.array([(1,2,7,9),(4,5,6,9)])
c = np.array([(1,2,3),(4,5,6),(7,8,9),(4,5,6)])
array = [a,b,c]

print(multiply_matrices(array))

[[ 298  365  432]
 [ 886 1082 1278]
 [1168 1421 1674]]


In [0]:
# Test case 3: Multiplication of a 3X2, 4X4, and 4X3 

a = np.array([(1,2),(4,5),(7,5)])
b = np.array([(1,2,7,9),(4,5,6,9),(4,5,6,9),(4,5,6,9)])
c = np.array([(1,2,3),(4,5,6),(7,8,9),(4,5,6)])
array = [a,b,c]

print(multiply_matrices(array))

the folloing arrays are not compatible:

[[1 2]
 [4 5]
 [7 5]]

[[1 2 7 9]
 [4 5 6 9]
 [4 5 6 9]
 [4 5 6 9]]

None


In [0]:
# Test case 4: Multiplication of a 1X2 and 2X1
a = np.array([(4,2)])
b = np.array([(2),(7)])
array = [a,b]

print(multiply_matrices(array))

[[22]]


In [0]:
# Test case 5: Multiplication of a 2X1 and 1X2

a = np.array([(4,2)])
b = np.array([(2),(7)])
array = [b,a]

print(multiply_matrices(array))

[[ 8  4]
 [28 14]]
