<a href="https://colab.research.google.com/github/erick1439/CAP4630-Wocjan/blob/master/HW_4/Problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Description:**

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

#**Implementation:**

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):

  # Special cases in order to avoid errors on the computation.
  if input_mat.shape[0] != input_mat.shape[1]:
    return "Input Matrix is not square"

  if s <= 0:
    return "Make sure the value in s is valid"

  if s > input_mat.shape[0]:
    return "The value in s is largert the input size"

  # Statements that calculate the new length of the result matrix.
  result_mat = np.zeros((input_mat.shape[0] // s, input_mat.shape[0] // s))

  # Perform the max pooling operation
  for col in range(result_mat.shape[0]):
    for row in range(result_mat.shape[0]):
      x_bound = row * s
      y_bound = col * s
      result_mat[col][row] = np.amax(input_mat[y_bound:y_bound + s, x_bound:x_bound + s])

  return result_mat

#**Custom Test Cases:**

In [0]:
# Test case 1:
input_mat = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

print(maxpooling2d(input_mat, 2), end="\n\n")

# Test case 2:
input_mat = np.array([[1, 1, 1],
                      [2, 2, 2],
                      [3, 3, 3]])

print(maxpooling2d(input_mat, 1), end="\n\n")

# Test case 3:
input_mat = np.array([[1, 2, 3],
                      [4, 5, 6], 
                      [7, 8, 9]])

print(maxpooling2d(input_mat, 3))


[[ 6.  8.]
 [14. 16.]]

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]

[[9.]]


# **Given Test cases:**

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 4, 2, 1],
                           [1, 2, 4, 2],
                           [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                              [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                           [2, 4, 2, 1, 0, 3],
                           [1, 2, 4, 2, 4, 5],
                           [2, 1, 2, 1, 2, 1],
                           [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append("Input Matrix is not square")


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
Input Matrix is not square
Correct output!


#**Resources:**

https://keras.io/layers/pooling/

https://www.youtube.com/watch?v=8oOgPUO-TBY