<a href="https://colab.research.google.com/github/erick1439/CAP4630-Wocjan/blob/master/HW_4/Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Description:**

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

#**Implementation:**

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):
    # Special cases in order to avoid errors on the computation.

    if kernel_mat.shape[0] != kernel_mat.shape[1]:
      return "Kernel matrix is not square"
    
    if input_mat.shape[0] != input_mat.shape[1]:
      return "Input matrix is not square"

    if kernel_mat.shape[0] > input_mat.shape[0]:
      return "Kernel size is greater than the input size"

    # Statements that calculate the new length of the result matrix.
    result_mat = np.zeros((input_mat.shape[0] - kernel_mat.shape[0] + 1, input_mat.shape[0] - kernel_mat.shape[0] + 1))

    # Loops that calculate the convolution computations
    for col in range(result_mat.shape[0]):
        for row in range(result_mat.shape[1]):
          x_bound = row + kernel_mat.shape[0];
          y_bound = col + kernel_mat.shape[0]
          temp_mat = np.multiply(input_mat[col:y_bound, row:x_bound], kernel_mat)
          result_mat[col][row] = np.sum(temp_mat)

    return result_mat

# **Custom Test cases:**

In [0]:
# Test case 1: 
input_mat = np.array([[1, 2, 3],
                      [1, 2, 3],
                      [1, 2, 3]])

kernel_mat = np.array([[1, 1],
                       [1, 1]])

print(conv2d(input_mat, kernel_mat), end="\n\n")

# Test case 2:
input_mat = np.array([[1, 1, 1],
                      [2, 2, 2],
                      [3, 3, 3]])

kernel_mat = np.array([[1,0],
                       [0,1]])

print(conv2d(input_mat, kernel_mat), end="\n\n")

# Test case 3: (kernel_len > input_len)
input_mat = np.array([[1,0],
                      [0,1]])

kernel_mat = np.array([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3]])

print(conv2d(input_mat, kernel_mat), end="\n\n")



[[ 6. 10.]
 [ 6. 10.]]

[[3. 3.]
 [5. 5.]]

Kernel size is greater than the input size



# **Provided test cases:**

In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                           [2, 1, 2, 1],
                           [1, 2, 1, 2],
                           [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                              [4, 2, 4],
                              [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                          [0, 1, 0, 0],
                          [0, 0, 1, 0],
                          [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0], 
                            [0, 1]]))

expected_mat.append(np.array([[2, 0, 0], 
                              [0, 2, 0], 
                              [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, -1],
                            [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], 
                              [-1,  1, -1],
                              [ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                           [0, 1, 0, 0],
                           [0, 0, 1, 0],
                           [0, 0, 0, 1]]))


kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                           [-1, 0]]))

kernel_mat.append(np.array([[1, 0, 0, 0],
                            [0, 1, 0, 0],
                            [0, 0, 1, 0],
                            [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  #output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

[]
Correct output!



#**Resources:**

https://keras.io/layers/convolutional/

https://www.youtube.com/watch?v=sTTuaNp5LTw